#!/usr/bin/env python3
"""gen_glyphsheet.py -- draw a sheet of every code-page glyph that is NOT a
straight copy of the IBM VGA CP437 bitmap, into wc-glyphs.png.

The code-page face (src/wcfont.c) is generated by gen_font.py. Most of its
glyphs are transcribed 1:1 from the public-domain IBM VGA 8x8 CP437 face, but
the app's repertoire is "anything CP437 or Windows-1252 can name", and CP437
has no bitmap at all for a good part of that. Those gaps were filled in four
different ways, and this sheet shows each one so the stand-ins are not a
mystery:

    composed   a plain CP437 letter shifted down two rows, accent stamped in
    drawn      a bitmap written out by hand (dashes, ellipsis, superscripts)
    OEM slots  a CP437 control-slot bitmap the DOS page exposes as a graphic
    hand-drawn a real bitmap written out for a code point CP437 never had

Nothing on this sheet is an ASCII stand-in any more: gen_font.py asserts that
every code point in the repertoire resolves to a real bitmap.

Everything is read straight out of gen_font.py, so the sheet cannot drift from
the font that gets linked in.

Run from anywhere:  python tools/gen_glyphsheet.py [scale]
"""

import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
os.chdir(HERE)

import gen_font as G          # noqa: E402  (authoritative glyph source)

GW, GH = G.W, G.H             # 8 x 9
# code points with a real hand-drawn bitmap of their own
HAND_NAME = {
    0x00A4: "currency sign", 0x00A9: "copyright", 0x00AE: "registered",
    0x00B8: "cedilla", 0x00BE: "three quarters", 0x00D0: "ETH",
    0x00D8: "O slash", 0x00DE: "THORN", 0x00F0: "eth", 0x00F8: "o slash",
    0x00FE: "thorn", 0x0152: "OE", 0x0153: "oe", 0x02C6: "circumflex",
    0x02DC: "small tilde", 0x2018: "left single quote",
    0x2019: "right single quote", 0x201A: "single low quote",
    0x201C: "left double quote", 0x201D: "right double quote",
    0x201E: "double low quote", 0x2020: "dagger", 0x2021: "double dagger",
    0x2030: "per mille", 0x2039: "left angle quote", 0x203A: "right angle quote",
    0x20AC: "euro", 0x2122: "trade mark",
}

DRAWN_NAME = {
    0x00B9: "superscript 1", 0x00B3: "superscript 3", 0x00D7: "times sign",
    0x00A6: "broken bar", 0x00A8: "diaeresis", 0x00AF: "macron",
    0x00B4: "acute accent", 0x2013: "en dash", 0x2014: "em dash",
    0x2026: "ellipsis",
}

# what the DOS page prints at each control slot (the CP437 graphic set)
OEM_NAME = {
    0x263A: "smiley", 0x263B: "smiley inverse", 0x2665: "heart",
    0x2666: "diamond", 0x2663: "club", 0x2660: "spade", 0x2022: "bullet",
    0x25D8: "inverse bullet", 0x2642: "male", 0x2640: "female",
    0x266B: "beamed note", 0x263C: "sun", 0x25BA: "right pointer",
    0x25C4: "left pointer", 0x2195: "up down arrow", 0x203C: "double bang",
    0x00B6: "pilcrow", 0x00A7: "section", 0x25AC: "black rectangle",
    0x21A8: "bar up down arrow", 0x2191: "up arrow", 0x2193: "down arrow",
    0x2192: "right arrow", 0x2190: "left arrow", 0x221F: "right angle",
    0x2194: "left right arrow", 0x25B2: "up triangle", 0x25BC: "down triangle",
    0x2302: "house",
}

# ---------------------------------------------------------------- sections --
SECTIONS = [
    ("composed - plain letter shifted down 2 rows, accent stamped on top",
     [(cp, "%s + %s" % (b, a)) for cp, (b, a) in sorted(G.COMPOSE.items())]),
    ("drawn - bitmap written out by hand, no CP437 shape to copy",
     [(cp, DRAWN_NAME.get(cp, "")) for cp in sorted(G.DRAWN)]),
    ("OEM control slots - DOS graphic bitmap exposed by the OEM character set",
     [(cp, "0x%02X %s" % (b, OEM_NAME.get(cp, "")))
      for b, cp in sorted(G.OEM_LO.items())]),
    ("hand-drawn - a real bitmap written for a code point CP437 never had",
     [(cp, HAND_NAME.get(cp, "")) for cp in sorted(G.HAND)]),
    ("rebuilt - source '|' was a broken bar, replaced with a solid stem",
     [(0x7C, "solid stem")]),
]

# ------------------------------------------------------------------- layout --
SCALE = 4                     # glyph magnification
MARGIN = 16
CELLW, CELLH = 158, 54
COLS = 5
HEADH = 16                    # section header bar
SECTGAP = 12
TXTS = 1                      # label magnification


def text_w(s):
    return len(s) * GW * TXTS


def put(px, w, h, s, x, y, ink=0):
    """Draw ASCII/CP437 text with the face itself: glyph_for() returns one
    row byte per scan line, MSB = leftmost pixel."""
    for ch in s:
        for ry, row in enumerate(G.glyph_for(ord(ch))):
            for rx in range(GW):
                if not (row >> (7 - rx)) & 1:
                    continue
                for dy in range(TXTS):
                    for dx in range(TXTS):
                        X, Y = x + rx * TXTS + dx, y + ry * TXTS + dy
                        if 0 <= X < w and 0 <= Y < h:
                            px[X, Y] = ink
        x += GW * TXTS
    return x


def blit_glyph(px, w, h, cp, x, y, scale):
    for ry, row in enumerate(G.glyph_for(cp)):
        for rx in range(GW):
            if not (row >> (7 - rx)) & 1:
                continue
            for dy in range(scale):
                for dx in range(scale):
                    X, Y = x + rx * scale + dx, y + ry * scale + dy
                    if 0 <= X < w and 0 <= Y < h:
                        px[X, Y] = 0


def main():
    sections = [(t, e) for t, e in SECTIONS]
    width = MARGIN * 2 + COLS * CELLW
    height = MARGIN
    for _, entries in sections:
        rows = (len(entries) + COLS - 1) // COLS
        height += HEADH + 4 + rows * CELLH + SECTGAP
    height += MARGIN

    img = Image.new("L", (width, height), 255)
    px = img.load()

    put(px, width, height, "WC code-page glyphs that are not a plain CP437 copy",
        MARGIN, 4, 0)
    y = MARGIN + 12

    for title, entries in sections:
        for yy in range(y, y + HEADH):
            for xx in range(MARGIN, width - MARGIN):
                px[xx, yy] = 0
        put(px, width, height, "%s  (%d)" % (title, len(entries)),
            MARGIN + 3, y + 4, 255)
        y += HEADH + 4
        for i, (cp, note) in enumerate(entries):
            cx = MARGIN + (i % COLS) * CELLW
            cy = y + (i // COLS) * CELLH
            # cell frame
            for xx in range(cx, cx + CELLW - 6):
                px[xx, cy] = 200
                px[xx, cy + CELLH - 6] = 200
            for yy in range(cy, cy + CELLH - 6):
                px[cx, yy] = 200
                px[cx + CELLW - 7, yy] = 200
            blit_glyph(px, width, height, cp, cx + 5, cy + 5, SCALE)
            lx = cx + 5 + GW * SCALE + 6
            put(px, width, height, "U+%04X" % cp, lx, cy + 6, 0)
            put(px, width, height, note, lx, cy + 22, 90)
        y += ((len(entries) + COLS - 1) // COLS) * CELLH + SECTGAP

    big = img.resize((img.width * 2, img.height * 2), Image.NEAREST)
    big.save("wc-glyphs.png")
    total = sum(len(e) for _, e in sections)
    print("wrote wc-glyphs.png (%dx%d, %d glyphs, scale %d)"
          % (big.width, big.height, total, 2))

    # console ASCII dump, so the shapes are checkable without opening a PNG
    for title, entries in sections:
        print("\n== %s ==" % title)
        for cp, note in entries:
            rows = G.glyph_for(cp)
            print("  U+%04X %-16s %s" % (cp, note, " / ".join(
                "".join("#" if (r >> (7 - c)) & 1 else "." for c in range(8))
                for r in rows)))

    # how many code points the face still cannot draw at all
    blanks = [cp for cp in G.CPS if not any(
        (r >> c) & 1 for r in G.glyph_for(cp) for c in range(8))]
    print("\ncode points with a blank bitmap: %d %s"
          % (len(blanks), "".join("U+%04X " % c for c in blanks) or "(none)"))


if __name__ == "__main__":
    main()
