#!/usr/bin/env python3
"""
gen_lucida.py -- rasterize C:/Windows/Fonts/lucon.ttf into src/lucfont.{c,h}.

Lucida Console is monospaced at 0.6025 em, so at em=13 the advance is 7.83 px
and an 8 px cell holds it exactly. The cell height, and where the baseline sits
inside it, are measured from the actual ink of every glyph rather than trusted
from the hhea/OS2 design metrics -- those are generous and would waste rows on a
224 px tall screen.

The code point set is the same one gen_font.py covers for the bundled CP437
face (ASCII + everything CP437 / Windows-1252 can name), so switching between
the two faces never blanks a character out. Lucida Console happens to cover all
of them: Latin-1 fully, the CP437 light/double box-drawing subset and the eight
CP437 shade/block code points.

Run:  python tools/gen_lucida.py [em] [--preview]
"""

import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
import gen_font  # noqa: E402  -- reuse NEEDED and the two byte->codepoint tables

LU = r"C:\Windows\Fonts\lucon.ttf"
NAME = "Lucida Console"
THRESH = 100          # of 255: biased low so thin stems survive the 1-bit cut


def build(em):
    f = ImageFont.truetype(LU, em)

    # --- 1. measure the ink box over the whole repertoire -----------------
    probe = 96
    tmp = Image.new("L", (probe * 2, probe * 4), 0)
    d = ImageDraw.Draw(tmp)
    base = probe * 2
    top, bot = 0, 0
    for cp in sorted(gen_font.NEEDED):
        if cp == 0x20:
            continue
        d.text((probe, base), chr(cp), font=f, fill=255, anchor="ls")
    for cp in sorted(gen_font.NEEDED):
        if cp == 0x20:
            continue
        img = Image.new("L", (probe * 2, probe * 4), 0)
        dd = ImageDraw.Draw(img)
        dd.text((probe, base), chr(cp), font=f, fill=255, anchor="ls")
        bb = img.getbbox()
        if bb is None:
            continue
        top = max(top, base - bb[1])
        bot = max(bot, bb[3] - base)
    CH = top + bot
    CW = 8
    print("em=%d  ink above baseline=%d  below=%d  -> cell %dx%d" % (em, top, bot, CW, CH))

    # --- 2. rasterize every needed code point into its cell --------------
    def cell(cp):
        img = Image.new("L", (CW, CH), 0)
        if cp != 0x20:
            ImageDraw.Draw(img).text((0, top), chr(cp), font=f, fill=255, anchor="ls")
        px = img.load()
        rows = []
        for y in range(CH):
            b = 0
            for x in range(CW):
                if px[x, y] >= THRESH:
                    b |= 1 << (7 - x)
            rows.append(b)
        return rows

    blank_ok = {0x20}
    blanks = []
    for cp in sorted(gen_font.NEEDED):
        if cp in blank_ok:
            continue
        if not any(cell(cp)):
            blanks.append(cp)
    if blanks:
        print("WARNING %d needed code points rasterized to nothing: %s"
              % (len(blanks), " ".join("U+%04X" % c for c in blanks)))

    # --- 3. blocks over the sorted code point set ------------------------
    cps = sorted(gen_font.NEEDED)
    blocks = []
    for cp in cps:
        if blocks and cp == blocks[-1][0] + blocks[-1][1]:
            blocks[-1][1] += 1
        else:
            blocks.append([cp, 1])
    assert len(blocks) < 256, "too many blocks"

    glyphs = []
    for start, length in blocks:
        for cp in range(start, start + length):
            glyphs.append(cell(cp) if cp in gen_font.NEEDED else [0] * CH)

    storage = (CW * CH + 31) >> 5

    def words(rows):
        bits = []
        for r in rows:
            for x in range(CW):
                bits.append((r >> (7 - x)) & 1)
        while len(bits) % 32:
            bits.append(0)
        out = []
        for i in range(0, len(bits), 32):
            v = 0
            for bit in bits[i:i + 32]:
                v = (v << 1) | bit
            out.append(v)
        return out

    data_lines = []
    for g in glyphs:
        data_lines.append("    " + ",".join("0x%08Xu" % v for v in words(g)) + ",")
    data_lines[-1] = data_lines[-1].rstrip(",")

    block_lines = []
    for start, length in blocks:
        block_lines.append("    (uint32_t)(0x%Xu << 12) | 0x%Xu," % (start, length))
    block_lines[-1] = block_lines[-1].rstrip(",")

    src = []
    w = src.append
    w("/* GENERATED by tools/gen_lucida.py -- do not edit by hand. */")
    w("")
    w("#include <gint/display.h>")
    w("#include <gint/defs/types.h>")
    w('#include "lucfont.h"')
    w("")
    w("/* Unicode blocks: pairs of (first code point, length) packed into one")
    w(" * word as (start << 12) | length. */")
    w("static uint32_t const luc_blocks[] = {")
    src.extend(block_lines)
    w("};")
    w("")
    w("/* Glyph bitmaps: %d glyphs x %d longwords, each row one byte, MSB first. */"
      % (len(glyphs), storage))
    w("static uint32_t const luc_data[] = {")
    src.extend(data_lines)
    w("};")
    w("")
    w("/* Declared with gint's own font_t so the compiler lays the bitfield byte,")
    w(" * the pointers and the trailing metrics out exactly the way gint's")
    w(" * renderer reads them. */")
    w("static font_t const luc_font = {")
    w('    "%s",' % NAME)
    w("    0, 0, 0, 0,              /* bold, italic, serif, mono */")
    w("    0,                       /* prop: fixed-width */")
    w("    %d,                      /* line_height */" % CH)
    w("    %d,                      /* data_height */" % CH)
    w("    %d,                      /* block_count */" % len(blocks))
    w("    %d,                      /* glyph_count */" % len(glyphs))
    w("    0,                       /* char_spacing: advance == width == %d px */" % CW)
    w("    (void *)luc_blocks,")
    w("    (void *)luc_data,")
    w("    { .width = %d, .storage_size = %d }" % (CW, storage))
    w("};")
    w("")
    w("font_t const *luc_font_get(void) { return &luc_font; }")
    w("")

    hdr = """/* GENERATED by tools/gen_lucida.py -- do not edit by hand. */
#ifndef LUCFONT_H
#define LUCFONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled Lucida Console face. Monospaced: a text column n
 * sits at x = n * LUC_W, exactly like the code-page font. */
#define LUC_W %d
#define LUC_H %d

/* Lucida Console, rasterized from the Windows "lucon.ttf". Covers the same
 * code points as the bundled code-page font, so either can be selected. */
font_t const *luc_font_get(void);

#endif
""" % (CW, CH)

    with open(os.path.join(ROOT, "src", "lucfont.c"), "w", encoding="ascii") as fh:
        fh.write("\n".join(src))
    with open(os.path.join(ROOT, "src", "lucfont.h"), "w", encoding="ascii") as fh:
        fh.write(hdr)

    print("blocks=%d glyphs=%d storage=%d bytes/glyph" % (len(blocks), len(glyphs), storage))
    print("font data = %d bytes" % (len(glyphs) * storage * 4))
    return cell, CW, CH


def preview(cell, CW, CH):
    """Mock a 396x224 editor screen with the 1-bit cells, so the result can be
    judged without a calculator."""
    W, H = 396, 224
    img = Image.new("L", (W, H), 255)
    px = img.load()
    lines = [
        "static int parse_int(const char *s) {",
        "    int neg = 0, v = 0;",
        "    if(*s == '-') { neg = 1; s++; }",
        "    while(*s >= '0' && *s <= '9') v = v*10 + *s++ - '0';",
        "    return neg ? -v : v;",
        "}",
        "",
        "Accents: \u00c9\u00c0\u00cd\u00dd\u00e9\u00e8\u00fc\u00f1\u00c7\u00df  Greek: \u03b1\u03b2\u03b3\u03c0\u03a3\u03a9",
        "Box: \u250c\u2500\u252c\u2500\u2510 \u251c\u2500\u253c\u2500\u2524",
        "     \u2514\u2500\u2534\u2500\u2518 \u2502 \u2591\u2592\u2593\u2588",
        "Symbols: \u00b0\u00b1\u00d7\u00f7\u2248\u2261\u221a\u207f\u00b2\u00b7  \u2190\u2191\u2192\u2193",
    ]
    for i, ln in enumerate(lines):
        y = 15 + i * (CH + 3)
        if y + CH > H - 15:
            break
        for j, ch in enumerate(ln):
            x = 2 + j * CW
            if x + CW > W:
                break
            rows = cell(ord(ch))
            for ry, rb in enumerate(rows):
                for rx in range(CW):
                    if (rb >> (7 - rx)) & 1:
                        px[x + rx, y + ry] = 0
    # status bar + soft-key bar
    for y in range(0, 15):
        for x in range(W):
            px[x, y] = 0
    for y in range(H - 15, H):
        for x in range(W):
            px[x, y] = 0
    for j, ch in enumerate("F1 Save  F5 Browser  F6 Exit"):
        x = 2 + j * CW
        rows = cell(ord(ch))
        for ry, rb in enumerate(rows):
            for rx in range(CW):
                if (rb >> (7 - rx)) & 1:
                    px[x + rx, 2 + ry] = 255
    for j, ch in enumerate("/TEXTEDIT/LUCIDA.TXT *"):
        x = 2 + j * CW
        rows = cell(ord(ch))
        for ry, rb in enumerate(rows):
            for rx in range(CW):
                if (rb >> (7 - rx)) & 1:
                    px[x + rx, 2 + ry] = 255
    out = os.path.join(ROOT, "_lucida_mock.png")
    img.resize((W * 2, H * 2), Image.NEAREST).save(out)
    print("wrote", out)


if __name__ == "__main__":
    argv = [a for a in sys.argv[1:] if not a.startswith("--")]
    em = int(argv[0]) if argv else 13
    cell, CW, CH = build(em)
    if "--preview" in sys.argv:
        preview(cell, CW, CH)
