/* GENERATED by tools/gen_ttf.py -- do not edit by hand. */
#ifndef CMS_FONT_H
#define CMS_FONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled "Comic Sans MS" face, cell-fitted to a fixed advance so a
 * text column n sits at x = n * CMS_W. */
#define CMS_W 10
#define CMS_H 13

font_t const *cms_font_get(void);

#endif
