/* GENERATED by tools/gen_ttf.py -- do not edit by hand. */
#ifndef CON_FONT_H
#define CON_FONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled "Consolas" face, cell-fitted to a fixed advance so a
 * text column n sits at x = n * CON_W. */
#define CON_W 8
#define CON_H 15

font_t const *con_font_get(void);

#endif
