/* GENERATED by tools/gen_lucida.py -- do not edit by hand. */
#ifndef LUCFONT_H
#define LUCFONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled Lucida Console face. Monospaced: a text column n
 * sits at x = n * LUC_W, exactly like the code-page font. */
#define LUC_W 8
#define LUC_H 13

/* Lucida Console, rasterized from the Windows "lucon.ttf". Covers the same
 * code points as the bundled code-page font, so either can be selected. */
font_t const *luc_font_get(void);

#endif
