/* GENERATED by tools/gen_ttf.py -- do not edit by hand. */
#ifndef NOT_FONT_H
#define NOT_FONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled "Noto Sans" face, cell-fitted to a fixed advance so a
 * text column n sits at x = n * NOT_W. */
#define NOT_W 10
#define NOT_H 14

font_t const *not_font_get(void);

#endif
