/* GENERATED by tools/gen_ttf.py -- do not edit by hand. */
#ifndef ROB_FONT_H
#define ROB_FONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled "Roboto" face, cell-fitted to a fixed advance so a
 * text column n sits at x = n * ROB_W. */
#define ROB_W 9
#define ROB_H 12

font_t const *rob_font_get(void);

#endif
