/* GENERATED by tools/gen_ttf.py -- do not edit by hand. */
#ifndef SS3_FONT_H
#define SS3_FONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled "Source Sans 3" face, cell-fitted to a fixed advance so a
 * text column n sits at x = n * SS3_W. */
#define SS3_W 9
#define SS3_H 14

font_t const *ss3_font_get(void);

#endif
