/* GENERATED by gen_font.py -- do not edit by hand. */
#ifndef WCFONT_H
#define WCFONT_H

#include <gint/display.h>
#include <gint/defs/types.h>

/* Cell size of the bundled code-page font. Monospaced: every character is
 * exactly WC_W pixels wide, so a text column n starts at x = n * WC_W. */
#define WC_W 8
#define WC_H 9

/* The font, covering ASCII, Latin-1, CP437 box drawing / blocks / symbols,
 * Greek and the Windows-1252 punctuation range. */
font_t const *wc_font_get(void);

/* High-half byte -> Unicode code point, for the DOS/IBM (OEM) and
 * Windows (ANSI) character sets. Index with (byte - 0x80). */
extern uint16_t const wc_cp437[128];
extern uint16_t const wc_cp1252[128];

/* OEM control slots: raw byte 0x00-0x1F -> code point, 0 when the slot has no
 * graphic. The DOS page puts its smileys, card suits and arrows here; the
 * other two pages leave control bytes as '.' and never look at this table.
 * DEL (0x7F) is the house U+2302, which main.c substitutes for the OEM set. */
extern uint16_t const wc_cp437_lo[32];

#endif
